export const LIST_USERS = "LIST_USERS"
export const LIST_USERS_SUCCESS = "LIST_USERS_SUCCESSS"
export const LIST_USERS_ERROR = "LIST_USERS_ERROR"

export const ADD_USER = 'ADD_USER'
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS'
export const ADD_USER_ERROR = 'ADD_USER_ERROR'

export const UPDATE_USER = 'UPDATE_USER'
export const DELETE_USER = 'DELETE_USER'

export const ADD_ADDRESS = 'ADD_ADDRESS'
export const ADD_ADDRESS_SUCCESS = 'ADD_ADDRESS_SUCCESS'
export const ADD_ADDRESS_ERROR = 'ADD_ADDRESS_ERROR'

export const UPDATE_ADDRESS = 'UPDATE_ADDRESS'
export const DELETE_ADDRESS = 'DELETE_ADDRESS'
